# Builds src/SettingsIndex.h: every control label on every Settings page, so the Settings search can say
# "Linux-style title bars - in Window Behavior". Run by build.ps1 before compiling (safe to run by hand).
import re, os, sys
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def _read(p):
    return open(os.path.join(root, p), encoding='utf-8', errors='surrogateescape').read()
# main.cpp is a list of #include "src/app/NN_*.cpp" sections now; read them in order as one source
src = re.sub(r'^#include "(src/app/[^"]+\.cpp)".*$', lambda m: _read(m.group(1)), _read('main.cpp'), flags=re.M)

# the page switch lives between the page-title draw and the content-height bookkeeping at its end
start = src.find('TextAt(dl,g_fBig,26,V(mx,my),WithA(COL_INK,al),SET_PAGES[g_setPage]);')
end = src.find('g_setContentH = (my+g_setScroll) - myStart;')
if start < 0 or end < 0:
    print('gen_settings_index: markers not found'); sys.exit(0)
body = src[start:end]

case_re = re.compile(r'\n\s*case (SP_[A-Z_]+)\s*:\s*(?:default\s*:\s*)?\{')
label_re = re.compile(r'\b(toggle|cycler|slider|textField|header|section|kv)\(\s*"((?:[^"\\]|\\.)+)"')
btn_re = re.compile(r'\bbuttons\(\{\s*"((?:[^"\\]|\\.)+)"(?:\s*,\s*"((?:[^"\\]|\\.)+)")?(?:\s*,\s*"((?:[^"\\]|\\.)+)")?')

cases = [(m.group(1), m.start()) for m in case_re.finditer(body)]
seen = set(); out = []
for i, (sp, pos) in enumerate(cases):
    chunk = body[pos: cases[i+1][1] if i+1 < len(cases) else len(body)]
    for m in label_re.finditer(chunk):
        lab = m.group(2)
        if '\\x' in lab or len(lab) < 3: continue
        key = (sp, lab)
        if key in seen: continue
        seen.add(key); out.append((sp, lab, m.group(1)))
    for m in btn_re.finditer(chunk):
        for g in m.groups():
            if g and len(g) >= 3 and (sp, g) not in seen:
                seen.add((sp, g)); out.append((sp, g, 'button'))

lines = ['// generated by tools/gen_settings_index.py - do not edit', '#pragma once',
         'struct SetIndexEntry { int page; const char* label; const char* kind; };',
         'static const SetIndexEntry SET_INDEX[] = {']
for sp, lab, kind in out:
    lines.append('    { %s, "%s", "%s" },' % (sp, lab, kind))
lines.append('};')
lines.append('static const int SET_INDEX_N = (int)(sizeof(SET_INDEX)/sizeof(SET_INDEX[0]));')
path = os.path.join(root, 'src', 'SettingsIndex.h')
new = '\n'.join(lines) + '\n'
old = open(path, encoding='utf-8').read() if os.path.exists(path) else ''
if new != old:
    open(path, 'w', encoding='utf-8', newline='\n').write(new)
print('gen_settings_index: %d entries' % len(out))
