// Generated by scratch/mksubset.py - do not edit by hand.
// Material Symbols Rounded (Google, Apache-2.0) subset to the glyphs Aether draws.
// See THIRD-PARTY.md. Names are BOTH the freedesktop names ThemedSym already asks
// for and the Material Symbols names, so either spelling resolves.
#pragma once
#include <cstdint>

struct MIcon { const char* name; unsigned short cp; };
static const unsigned short MICON_LO = 0xE02B, MICON_HI = 0xF8C7;

static const MIcon MICONS[] = {
    { "audio-input-microphone", 0xE31D },   // mic
    { "configure", 0xE8B8 },   // settings
    { "input-keyboard", 0xE312 },   // keyboard
    { "microphone-sensitivity-muted", 0xE02B },   // mic_off
    { "network-bluetooth", 0xE1A7 },   // bluetooth
    { "network-vpn", 0xE0DA },   // vpn_key
    { "network-wired-activated", 0xEB2F },   // lan
    { "network-wireless-connected-100", 0xE63E },   // wifi
    { "network-wireless-disconnected", 0xE648 },   // wifi_off
    { "run-build-clean", 0xE28D },   // mop
    { "security-high", 0xE9E0 },   // shield
    { "system-lock-screen", 0xE899 },   // lock
    { "system-shutdown", 0xF8C7 },   // power_settings_new
    { "view-calendar-month", 0xEBCC },   // calendar_month
    { "view-calendar-symbolic", 0xE935 },   // calendar_today
    { "weather-clear", 0xF157 },   // clear_day
    { "weather-clear-night", 0xF159 },   // bedtime
    { "air", 0xEFD8 },   // air
    { "apps", 0xE5C3 },   // apps
    { "battery_alert", 0xE19C },   // battery_alert
    { "battery_charging_full", 0xE1A3 },   // battery_charging_full
    { "battery_full", 0xE1A5 },   // battery_full
    { "bedtime", 0xF159 },   // bedtime
    { "bluetooth", 0xE1A7 },   // bluetooth
    { "bluetooth_connected", 0xE1A8 },   // bluetooth_connected
    { "bluetooth_disabled", 0xE1A9 },   // bluetooth_disabled
    { "brightness_6", 0xE3AB },   // brightness_6
    { "calendar_month", 0xEBCC },   // calendar_month
    { "calendar_today", 0xE935 },   // calendar_today
    { "check", 0xE668 },   // check
    { "chevron_left", 0xE5CB },   // chevron_left
    { "chevron_right", 0xE5CC },   // chevron_right
    { "clear_day", 0xF157 },   // clear_day
    { "clear_night", 0xF159 },   // clear_night
    { "close", 0xE5CD },   // close
    { "cloud", 0xF15C },   // cloud
    { "cloudy", 0xF15C },   // cloudy
    { "content_copy", 0xE14D },   // content_copy
    { "dark_mode", 0xE51C },   // dark_mode
    { "dashboard", 0xE871 },   // dashboard
    { "delete", 0xE92E },   // delete
    { "desktop_windows", 0xE30C },   // desktop_windows
    { "developer_board", 0xE30D },   // developer_board
    { "expand_less", 0xE5CE },   // expand_less
    { "expand_more", 0xE5CF },   // expand_more
    { "foggy", 0xE818 },   // foggy
    { "folder", 0xE2C7 },   // folder
    { "grid_view", 0xE9B0 },   // grid_view
    { "keyboard", 0xE312 },   // keyboard
    { "lan", 0xEB2F },   // lan
    { "light_mode", 0xE518 },   // light_mode
    { "lock", 0xE899 },   // lock
    { "logout", 0xE9BA },   // logout
    { "memory", 0xE322 },   // memory
    { "mic", 0xE31D },   // mic
    { "mic_off", 0xE02B },   // mic_off
    { "monitor", 0xEF5B },   // monitor
    { "mop", 0xE28D },   // mop
    { "more_horiz", 0xE5D3 },   // more_horiz
    { "music_note", 0xE405 },   // music_note
    { "network_check", 0xE640 },   // network_check
    { "notifications", 0xE7F5 },   // notifications
    { "notifications_active", 0xE7F7 },   // notifications_active
    { "notifications_off", 0xE7F6 },   // notifications_off
    { "open_in_new", 0xE89E },   // open_in_new
    { "palette", 0xE40A },   // palette
    { "partly_cloudy_day", 0xF172 },   // partly_cloudy_day
    { "pause", 0xE034 },   // pause
    { "person", 0xF0D3 },   // person
    { "play_arrow", 0xE037 },   // play_arrow
    { "power_settings_new", 0xF8C7 },   // power_settings_new
    { "push_pin", 0xF10D },   // push_pin
    { "rainy", 0xF176 },   // rainy
    { "repeat", 0xE040 },   // repeat
    { "restart_alt", 0xF053 },   // restart_alt
    { "schedule", 0xEFD6 },   // schedule
    { "search", 0xEF7A },   // search
    { "settings", 0xE8B8 },   // settings
    { "shield", 0xE9E0 },   // shield
    { "shuffle", 0xE043 },   // shuffle
    { "signal_wifi_off", 0xE1DA },   // signal_wifi_off
    { "skip_next", 0xE044 },   // skip_next
    { "skip_previous", 0xE045 },   // skip_previous
    { "snowing", 0xE80F },   // snowing
    { "speed", 0xE9E4 },   // speed
    { "storage", 0xE1DB },   // storage
    { "terminal", 0xEB8E },   // terminal
    { "thermostat", 0xF076 },   // thermostat
    { "thunderstorm", 0xEBDB },   // thunderstorm
    { "tune", 0xE429 },   // tune
    { "volume_down", 0xE04D },   // volume_down
    { "volume_mute", 0xE04E },   // volume_mute
    { "volume_off", 0xE04F },   // volume_off
    { "volume_up", 0xE050 },   // volume_up
    { "vpn_key", 0xE0DA },   // vpn_key
    { "water_drop", 0xE798 },   // water_drop
    { "widgets", 0xE1BD },   // widgets
    { "wifi", 0xE63E },   // wifi
    { "wifi_1_bar", 0xE4CA },   // wifi_1_bar
    { "wifi_2_bar", 0xE4D9 },   // wifi_2_bar
    { "wifi_off", 0xE648 },   // wifi_off
};
static const int MICON_COUNT = (int)(sizeof(MICONS)/sizeof(MICONS[0]));
